// Fallback list of countries in case the API is not available
export const FALLBACK_COUNTRIES = [
  { name: { common: 'United States' } },
  { name: { common: 'Canada' } },
  { name: { common: 'United Kingdom' } },
  { name: { common: 'Germany' } },
  { name: { common: 'France' } },
  { name: { common: 'Australia' } },
  { name: { common: 'Japan' } },
  { name: { common: 'India' } },
  { name: { common: 'China' } },
  { name: { common: 'Brazil' } },
  { name: { common: 'Mexico' } },
  { name: { common: 'Spain' } },
  { name: { common: 'Italy' } },
  { name: { common: 'Netherlands' } },
  { name: { common: 'Sweden' } },
  { name: { common: 'Norway' } },
  { name: { common: 'Denmark' } },
  { name: { common: 'Finland' } },
  { name: { common: 'Switzerland' } },
  { name: { common: 'Austria' } },
  { name: { common: 'Belgium' } },
  { name: { common: 'Ireland' } },
  { name: { common: 'New Zealand' } },
  { name: { common: 'South Africa' } },
  { name: { common: 'Singapore' } },
  { name: { common: 'South Korea' } },
  { name: { common: 'Thailand' } },
  { name: { common: 'Malaysia' } },
  { name: { common: 'Philippines' } },
  { name: { common: 'Indonesia' } },
  { name: { common: 'Vietnam' } },
  { name: { common: 'Turkey' } },
  { name: { common: 'Russia' } },
  { name: { common: 'Poland' } },
  { name: { common: 'Czech Republic' } },
  { name: { common: 'Hungary' } },
  { name: { common: 'Romania' } },
  { name: { common: 'Bulgaria' } },
  { name: { common: 'Croatia' } },
  { name: { common: 'Slovenia' } },
  { name: { common: 'Slovakia' } },
  { name: { common: 'Estonia' } },
  { name: { common: 'Latvia' } },
  { name: { common: 'Lithuania' } },
  { name: { common: 'Portugal' } },
  { name: { common: 'Greece' } },
  { name: { common: 'Cyprus' } },
  { name: { common: 'Malta' } },
  { name: { common: 'Luxembourg' } },
  { name: { common: 'Iceland' } },
  { name: { common: 'Israel' } },
  { name: { common: 'United Arab Emirates' } },
  { name: { common: 'Saudi Arabia' } },
  { name: { common: 'Qatar' } },
  { name: { common: 'Kuwait' } },
  { name: { common: 'Bahrain' } },
  { name: { common: 'Oman' } },
  { name: { common: 'Jordan' } },
  { name: { common: 'Lebanon' } },
  { name: { common: 'Egypt' } },
  { name: { common: 'Morocco' } },
  { name: { common: 'Tunisia' } },
  { name: { common: 'Algeria' } },
  { name: { common: 'Libya' } },
  { name: { common: 'Sudan' } },
  { name: { common: 'Ethiopia' } },
  { name: { common: 'Kenya' } },
  { name: { common: 'Nigeria' } },
  { name: { common: 'Ghana' } },
  { name: { common: 'Senegal' } },
  { name: { common: 'Ivory Coast' } },
  { name: { common: 'Cameroon' } },
  { name: { common: 'Uganda' } },
  { name: { common: 'Tanzania' } },
  { name: { common: 'Zambia' } },
  { name: { common: 'Zimbabwe' } },
  { name: { common: 'Botswana' } },
  { name: { common: 'Namibia' } },
  { name: { common: 'Mauritius' } },
  { name: { common: 'Madagascar' } },
  { name: { common: 'Argentina' } },
  { name: { common: 'Chile' } },
  { name: { common: 'Colombia' } },
  { name: { common: 'Peru' } },
  { name: { common: 'Venezuela' } },
  { name: { common: 'Ecuador' } },
  { name: { common: 'Bolivia' } },
  { name: { common: 'Paraguay' } },
  { name: { common: 'Uruguay' } },
  { name: { common: 'Guyana' } },
  { name: { common: 'Suriname' } },
  { name: { common: 'French Guiana' } },
  { name: { common: 'Costa Rica' } },
  { name: { common: 'Panama' } },
  { name: { common: 'Guatemala' } },
  { name: { common: 'Honduras' } },
  { name: { common: 'El Salvador' } },
  { name: { common: 'Nicaragua' } },
  { name: { common: 'Belize' } },
  { name: { common: 'Jamaica' } },
  { name: { common: 'Cuba' } },
  { name: { common: 'Haiti' } },
  { name: { common: 'Dominican Republic' } },
  { name: { common: 'Puerto Rico' } },
  { name: { common: 'Trinidad and Tobago' } },
  { name: { common: 'Barbados' } },
  { name: { common: 'Bahamas' } },
  { name: { common: 'Antigua and Barbuda' } },
  { name: { common: 'Saint Kitts and Nevis' } },
  { name: { common: 'Saint Lucia' } },
  { name: { common: 'Saint Vincent and the Grenadines' } },
  { name: { common: 'Grenada' } },
  { name: { common: 'Dominica' } }
];

// Function to load countries from API with fallback
export const loadCountries = async (apiFunction) => {
  try {
    const response = await apiFunction();
    return response.data;
  } catch (error) {
    console.error('Failed to load countries from API:', error);
    return FALLBACK_COUNTRIES;
  }
};
